### ISSUE TITLE
Is it possible for you to build arm64 versions of the docker image?

### ISSUE THREAD

**Issue by driftywinds** [Harshraj9812/HR-Bot-JMusicBot#2]
It would be really useful since the official image does not exist!

**Comment by Harshraj9812** [comment]
Sure, Let me work on arm64 Image.

**Comment by Harshraj9812** [comment]
Hi @driftywinds 
Both arm64 & amd64 build are created. I don't have any of these devices to verify the image, please verify and confirm.
https://hub.docker.com/repository/docker/harshraj9812/hr-bot-jmusicbot/tags

**Comment by driftywinds** [comment]
> Hi @driftywinds Both arm64 & amd64 build are created. I don't have any of these devices to verify the image, please verify and confirm. https://hub.docker.com/repository/docker/harshraj9812/hr-bot-jmusicbot/tags

arm64 build seems to work!
